apiVersion: apps/v1
kind: Deployment
metadata:
  name: kishq-shoppy-app
  labels:
    app: kishq-shoppy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kishq-shoppy-app
  template:
    metadata:
      labels:
        app: kishq-shoppy-app
    spec:
      containers:
      - name: kishq-shoppy-app
        image: iamsaikishore/kishq-shoppy-app:replaceImageTag
        ports:
        - containerPort: 8080
