apiVersion: v1
kind: Service
  metadata:
    name: kishq-shoppy-app-service
  spec:
    type: NodePort
    ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    selector:
      app: kishq-shoppy-app
